name: vk
description: Application for VK experts.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tcard: ^1.3.5
  google_fonts: ^2.1.0
  provider: ^5.0.0
  http: ^0.13.3
  enum_to_string: ^2.0.1
  loading_indicator: ^2.1.1
  path_provider: ^2.0.2
  loading_alert_dialog: ^1.1.0
  adaptive_theme: ^2.2.0
  vk_login: ^1.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: VKIcons
      fonts:
        - asset: assets/fonts/VKIcons.ttf


flutter_intl:
  enabled: true
